# Generated by Django 5.0.1 on 2024-10-11 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='user_contact',
        ),
    ]
