# Generated by Django 5.0.1 on 2024-10-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_appointment_delete_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_appointment',
        ),
        migrations.DeleteModel(
            name='user_contact',
        ),
    ]
