# Generated by Django 5.0.1 on 2024-10-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('package', models.CharField(max_length=20)),
            ],
        ),
    ]
